import { Post } from "./Posts";

export const POSTS: Post[] = [
    {id: 0,
    bandId: 1,
    socialMediaId: 0,
    postText: "멤버들 그리고 줴퀘 땡큐",
    postImage: ["assets/postImages/bts/post0.jpg"], //url do fotki
    postDate: "11:40 AM · 30 dec 2021"}, //tez string bo zalezy od social media

    {id: 1,
    bandId: 1,
    socialMediaId: 0,
    postText: "아 생일축하한다 브로",
    postImage: [], //url do fotki
    postDate: "9:04 AM · 30 dec 2021"}, //tez string bo zalezy od social media

    {id: 2,
    bandId: 1,
    socialMediaId: 0,
    postText: "마이 브로 태형아\n 너가 부탁한 사진 올린다\n 사랑한다 -진",
    postImage: ["assets/postImages/bts/post2.jpg"], //url do fotki
    postDate: "9:03 AM · 30 dec 2021"}, //tez string bo zalezy od social media

    {id: 3,
        bandId: 1,
        socialMediaId: 0,
        postText: "My love\n Happy birthday bro.\n #홉필름 \n #큰태형 \n #HAPPYVDAY \n #태형이와아미는_꽃길을걷고있어",
        postImage: ["assets/postImages/bts/post3a.jpg", "assets/postImages/bts/post3b.jpg", "assets/postImages/bts/post3c.jpg", "assets/postImages/bts/post3d.jpg"], //url do fotki
        postDate: "6:52 PM · 29 dec 2021"}, //tez string bo zalezy od social media
  
    {id: 4,
        bandId: 1,
        socialMediaId: 0,
        postText: "아 이게 인스타감성이었나?",
        postImage: [], //url do fotki
        postDate: "6:52 PM · 9 dec 2021"}, //tez string bo zalezy od social media
  
      {id: 5,
        bandId: 1,
        socialMediaId: 0,
        postText: "my name is v 삼성 보고있나",
        postImage: [], //url do fotki
        postDate: "4:00 PM · 9 dec 2021"}, //tez string bo zalezy od social media
   {id: 6,
        bandId: 1,
        socialMediaId: 0,
        postText: "Hundreds of millions of stars ⭐ (it's not photoshopped)",
        postImage: ["assets/postImages/bts/post6.jpeg"], //url do fotki
        postDate: "4:00 AM · 8 dec 2021"}, //tez string bo zalezy od social media
  {id: 7,
        bandId: 1,
        socialMediaId: 0,
        postText: "진형 생일이 왠지 기네?\n 햅뻘떼쁘뤄",
        postImage: ["assets/postImages/bts/post7.jpeg"],
        postDate: "4:00 AM · 5 dec 2021"}, 
    {id: 8,
        bandId: 1,
        socialMediaId: 0,
        postText: "ㅋㅋㅋㅋㅋㅋㅋ",
        postImage: ["assets/postImages/bts/post8.jpeg"],
        postDate: "4:00 PM · 4 dec 2021"}, 
      {id: 9,
        bandId: 1,
        socialMediaId: 0,
        postText: "ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 내 사진첩에 유일한 형 엽사다.\n 진짜 다 잘생겨서 그나마 찾은게 이거야\n형 많이 사랑하고 생일 축하해 형\n생일 축하해",
        postImage: ["assets/postImages/bts/post9.jpeg"],
        postDate: "2:00 PM · 4 dec 2021"}, 
      {id: 10,
        bandId: 1,
        socialMediaId: 0,
        postText: "태형",
        postImage: [],
        postDate: "1:00 PM · 4 dec 2021"}, 
      {id: 11,
        bandId: 1,
        socialMediaId: 0,
        postText: "쫜 생일축하해~",
        postImage: [],
        postDate: "11:00 AM · 4 dec 2021"}, 
      {id: 12,
        bandId: 1,
        socialMediaId: 0,
        postText: "늘 대리 만족을 해주는 얼굴\n #WWH 우리형 생일축하해요 \n사랑해 형!!건강하자!!",
        postImage: ["assets/postImages/bts/post12a.jpeg","assets/postImages/bts/post12b.jpeg","assets/postImages/bts/post12c.jpeg","assets/postImages/bts/post12d.jpeg"],
        postDate: "2:00 PM · 3 dec 2021"}, 
      {id: 13,
        bandId: 1,
        socialMediaId: 0,
        postText: "잊지 않을게요\n사랑합니다",
        postImage: ["assets/postImages/bts/post13a.jpeg", "assets/postImages/bts/post13b.jpeg"],
        postDate: "4:00 PM · 4 dec 2021"}, 
      {id: 14,
        bandId: 1,
        socialMediaId: 0,
        postText: "7FATES: CHAKHO is now coming.\nDon't miss out the unreleased behind the scenes!",
        postImage: ["assets/postImages/bts/post14.jpeg"],
        postDate: "4:00 PM · 4 dec 2021"}, 
      {id: 15,
        bandId: 1,
        socialMediaId: 1,
        postText: "Every moment we connected this year🌏 were our most Butter-ful moments, #BTSARMY! Thank you for a Butterful 2021",
        postImage: [],
        postDate: "18 December 2021 o 16:00 "}, 
      {id: 16,
        bandId: 1,
        socialMediaId: 1,
        postText: "We had so much fun at iHeartRadios Jingle Ball this year, and now you can watch our performance tonight!💜 Put your TVs on The CW at 8/7c!",
        postImage: ["assets/postImages/bts/post16.jpg"],
        postDate: "16 December 2021"}, 
      {id: 17,
        bandId: 1,
        socialMediaId: 1,
        postText: "Every day feels like holidays with #BTS_Butter (Holiday Remix)! 🎁\n☃Listen now: https://ingrv.es/butterholidayremix",
        postImage: [],
        postDate: "5 December 2021"}, 
      {id: 18,
        bandId: 1,
        socialMediaId: 1,
        postText: "This is a huge honor🙏 Thanks to everyone who supports our music journey! 💜 Recording Academy / GRAMMYs  #GRAMMYs #BTS #방탄소년단",
        postImage: ["assets/postImages/bts/post18.jpg"],
        postDate: "24 November 2021"}, 
      {id: 19,
        bandId: 1,
        socialMediaId: 1,
        postText: "BTS PERMISSION TO DANCE ON STAGE - LA \nOfficial Merch Booth Map | 공식 상품 부스 맵\n📅NOV 26~28 , NOV 30~DEC 2 (PST)\n📍LA SoFi STADIUM",
        postImage: ["assets/postImages/bts/post19a.jpg","assets/postImages/bts/post19b.jpg"],
        postDate: "24 November 2021"}, 
      {id: 20,
        bandId: 1,
        socialMediaId: 1,
        postText: "",
        postImage: ["assets/postImages/bts/post20a.jpg","assets/postImages/bts/post20b.jpg","assets/postImages/bts/post20c.jpg","assets/postImages/bts/post20d.jpg","assets/postImages/bts/post20e.jpg","assets/postImages/bts/post20f.jpg","assets/postImages/bts/post20g.jpg","assets/postImages/bts/post20h.jpg","assets/postImages/bts/post20i.jpg","assets/postImages/bts/post20j.jpg"],
        postDate: "2 November 2021"},
  
                {id: 21,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA MAP 🗺",
        postImage: ["assets/postImages/bts/post21.jpg"],
        postDate: "8 weeks"},
                {id: 22,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA OFFLINE 🏟\nCONCERT | MERCHANDISE | LIVE PLAY",
        postImage: ["assets/postImages/bts/post22.jpg"],
        postDate: "8 weeks"},
                {id: 23,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA ONLINE 🖥\nONLINE LIVE STREAMING",
        postImage: ["assets/postImages/bts/post23.jpg"],
        postDate: "8 weeks"},
                {id: 24,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post24.jpg"],
        postDate: "8 weeks"},
                {id: 25,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post25.jpg"],
        postDate: "8 weeks"},
                {id: 26,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post26.jpg"],
        postDate: "8 weeks"},
                {id: 27,
        bandId: 1,
        socialMediaId: 2,
        postText: "OW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post27.jpg"],
        postDate: "8 weeks"},
                {id: 28,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post28.jpg"],
        postDate: "8 weeks"},
                {id: 29,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post29.jpg"],
        postDate: "12 weeks"},
        {id: 30,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO DANCE WITH BTS - ONLINE STREAMING GUIDE\n- 티켓 구매 : 위버스샵\n- 시청 페이지: venewlive.com/concerts/bts-ptd-onstage\n- 판매기간\n[사운드체크 스트리밍 포함 상품]\n▶ 2021년 10월 1일(금) 12 PM ~ 2021년 10월 24일(일) 2:59 PM (KST)",
        postImage: ["assets/postImages/bts/post30.jpg"],
        postDate: "8 weeks"},
        {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "HAPPY BIRTHDAY JENNIE \n2022.01.16",
        postImage: ["assets/postImages/bp/1.jpg"],
        postDate: "4:00 PM · 15 Jan 2022"},
                {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "#LISA 'MONEY' EXCLUSIVE PERFORMANCE VIDEO HITS 400 MILLION VIEWS \n @Youtube\nBLINKs worldwide, thank you so much!\n‘MONEY’ EXCLUSIVE PERFORMANCE VIDEO",
        postImage: ["assets/postImages/bp/2.jpg"],
        postDate: "7:38 AM · 10 Jan 2022"},
          {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "#LISA 'LALISA' M/V HITS 400 MILLION VIEWS @Youtube\n BLINKs worldwide, thank you so much!\n 'LALISA' M/V",
        postImage: ["assets/postImages/bp/3.jpg"],
        postDate: "7:49 AM · 9 Jan 2022"},
          {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "HAPPY BIRTHDAY JISOO \n2022.01.03",
        postImage: ["assets/postImages/bp/4.jpg"],
        postDate: "4:01 PM · 2 Jan 2022"},
          {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "Hit you with that #DDUDUDDUD Items inspired by the legendary #BLACKPINK single are out now on ZEPETO",
        postImage: ["assets/postImages/bp/5.jpg"],
        postDate: "9:01 AM · 21 dec 2021"},
          {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "#BLACKPINK ‘Forever Young’ DANCE PRACTICE VIDEO HITS 200 MILLION VIEWS @YouTube\n BLINKs worldwide, thank you so much! 'Forever Young' DANCE PRACTICE VIDEO",
        postImage: ["assets/postImages/bp/6.jpg"],
        postDate: "2:37 AM · 13 dec 2021"},
          {id: 31,
        bandId: 2,
        socialMediaId: 0,
        postText: "#BLACKPINK ‘STAY’ M/V HITS 300 MILLION VIEWS \n@YouTube \nBLINKs worldwide, thank you so much!",
        postImage: ["assets/postImages/bp/7.jpg"],
        postDate: "12:01 AM · 12 dec 2021"},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 0,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 0,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 0,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
          {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "LISA 'LALISA' M/V\n📺NAVER TV: https://tv.naver.com/v/22377351\n 🎬YouTube: https://youtu.be/awkkyBH2zEo",
        postImage: [""],
        postDate: "21 Janurary 2022"},
                    {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "HAPPY BIRTHDAY JENNIE 🎉\n✅ 2022.01.16",
        postImage: ["assets/postImages/bp/8.jpg"],
        postDate: "15 Janurary 2022"},
                    {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "히트송 스티커 메들리 디자인, 멤버들의 사인이 새겨진 콘서트 티켓 디자인, 월드투어 애프터파티 패스 디자인 등 전 세계 블링크들을 위한 다채로운 스페셜 한정 디자인을 선보인답니다. 블랙핑크를 향한 여러분의 사랑을 리미티드 테크 에디션으로 트렌디하고 유니크하게 펼쳐보세요. \n한정 수량으로 망설이면 놓치는 #블랙핑크 리미티드 에디션! 지금 바로 Get 해 보세요!",
        postImage: ["assets/postImages/bp/9.jpg"],
        postDate: "21 December 2021"},
                    {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "Thank you so much for streaming #LALISA and #MONEY on Spotify",
        postImage: ["assets/postImages/bp/10.jpg"],
        postDate: "9 December 2021"},
                    {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "Thank you so much for streaming #OnTheGround and #Gone on Spotify 🎵",
        postImage: ["assets/postImages/bp/11.jpg"],
        postDate: "9 December 2021"},
                    {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "BLACKPINK‘s #THEALBUM is now in #DolbyAtmos 🎶\nStream #SpatialAudio of THE ALBUM only on Apple Music",
        postImage: [""],
        postDate: "8 December 2021"},
                    {id: 31,
        bandId: 2,
        socialMediaId: 1,
        postText: "LISA -LALISA- PHOTOBOOK [SPECIAL EDITION]\n⁍Release Date: 2022.01.10\n⁍Pre-order Date: 2021.12.08 ~ 2022.01.09\n⁍YG SELECT Price: ₩50,000 (Includes VAT)\n⁍Includes: Package Box + Hard Cover Photobook (224p) + Polaroid Set (5ea) + Accordion Postcard Set (8ea) + Tyvek Pouch (1ea) + Random Instax Photo Film (1 of 7/ Only 300ea)",
        postImage: ["assets/postImages/bp/13a.jpg", "assets/postImages/bp/13b.jpg", "assets/postImages/bp/13c.jpg"],
        postDate: "8 December 2021"},
        //             {id: 31,
        // bandId: 2,
        // socialMediaId: 1,
        // postText: "",
        // postImage: ["assets/postImages/bp/14.jpg"],
        // postDate: ""},
        //             {id: 31,
        // bandId: 2,
        // socialMediaId: 1,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //             {id: 31,
        // bandId: 2,
        // socialMediaId: 1,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
                    {id: 31,
        bandId: 2,
        socialMediaId: 2,
        postText: "#BLACKPINK #블랙핑크 #JENNIE #제니 #HAPPYBIRTHDAY #20220116 #YG",
        postImage: ["assets/postImages/bp/14.jpg"],
        postDate: "3d"},
          {id: 31,
        bandId: 2,
        socialMediaId: 2,
        postText: "#LISA #리사 #BLACKPINK #블랙핑크 #MONEY #EXCLUSIVE_PERFORMANCE_VIDEO #400MILLION #YOUTUBE #YG",
        postImage: ["assets/postImages/bp/15.jpg"],
        postDate: "1w"},
          {id: 31,
        bandId: 2,
        socialMediaId: 2,
        postText: "#LISA #리사 #BLACKPINK #블랙핑크 #LALISA #MV #400MILLION #YOUTUBE #YG",
        postImage: ["assets/postImages/bp/16.jpg"],
        postDate: "1w"},
          {id: 31,
        bandId: 2,
        socialMediaId: 2,
        postText: "#BLACKPINK #블랙핑크 #JISOO #지수 #HAPPYBIRTHDAY #20220103 #YG",
        postImage: ["assets/postImages/bp/17.jpg"],
        postDate: "2w"},
          {id: 31,
        bandId: 2,
        socialMediaId: 2,
        postText: "BLACKPINK GLOBAL OFFICIAL FANCLUB, BLINK MEMBERSHIP OPEN! Check out now on Weverse Shop!",
        postImage: ["assets/postImages/bp/18.jpg"],
        postDate: "4w"},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //   {id: 31,
        // bandId: 2,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
          {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "귀엽고 멋있고, 혼자 다 하는 #스트레이키즈 #리노, #뷰티쁠 2월호 커버를 장식했어요. 리노의 화보와 인터뷰, 영상까지 많은 기대 부탁드립니다! 예스24&알라딘&교보문고에서 예약 판매가 시작되었어요.",
        postImage: ["assets/postImages/skz/1.jpg"],
        postDate: "11:00 AM · 17 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "Please be aware of all instructions on the official reservation site before booking.",
        postImage: [""],
        postDate: "11:01 AM · 17 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "예매 페이지 안내사항을 반드시 숙지하시고 예매를 진행해주시기 바랍니다.",
        postImage: [""],
        postDate: "11:00 AM · 17 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "문 대통령은 두바이 엑스포는 2030년 부산 엑스포를 유치하고자 하는 한국에 많은 영감을 주고 있다며 2030년, 한국의 해양 수도 부산에서 다시 만나 ‘세계의 대전환’이라는 담대한 항해에 함께하길 희망한다고 말했습니다.",
        postImage: ["assets/postImages/skz/2.jpg","assets/postImages/skz/2a.jpg","assets/postImages/skz/2b.jpg"],
        postDate: "5:56 PM · 16 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "Stray Kids 2ND #LoveSTAY 'SKZ’S CHOCOLATE FACTORY' 예매 이벤트 안내",
        postImage: [""],
        postDate: "4:00 AM · 17 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "[스키지기] 내일 만나요 리야드! Stray Kids in Riyadh! See you tomorrow! @riyadhseason",
        postImage: ["assets/postImages/skz/3.jpg"],
        postDate: "6:02 PM · 13 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "[SKZ VLOG] I.N : I.N의 퐁당로그 4 English and Japanese subtitles are available!",
        postImage: ["assets/postImages/skz/4.jpg"],
        postDate: "12:00 PM · 13 Jan 2022"},
                    {id: 31,
        bandId: 0,
        socialMediaId: 0,
        postText: "Stray Kids 2ND #LoveSTAY 'SKZ’S CHOCOLATE FACTORY' TEASER IMAGE 02.12 6PM (KST) / 02.13 5PM (KST) + ONLINE https://bit.ly/3r9GCTU",
        postImage: ["assets/postImages/skz/5.jpg"],
        postDate: "4:00 AM · 13 Jan 2022"},
                    // {id: 31,
        // bandId: 0,
        // socialMediaId: 0,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //             {id: 31,
        // bandId: 0,
        // socialMediaId: 0,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
                    {id: 31,
        bandId: 0,
        socialMediaId: 1,
        postText: "Stray Kids 2ND #LoveSTAY 'SKZ'S CHOCOLATE FACTORY' STAY 2nd Generation FANCLUB Ticket Open 01.17 20:00 - 01.17 23:59 (KST) 🍫 YES24 bit.ly/3A0eLJZ (PC ONLY)",
        postImage: [""],
        postDate: "yesterday 11:01"},
           {id: 31,
        bandId: 0,
        socialMediaId: 1,
        postText: "[스키지기] 내일 만나요 리야드! Stray Kids in Riyadh! See you tomorrow!",
        postImage: ["assets/postImages/skz/6.jpg"],
        postDate: "13 Janurary 2021"},
           {id: 31,
        bandId: 0,
        socialMediaId: 1,
        postText: "[SKZ VLOG] I.N : I.N의 퐁당로그 4 English and Japanese subtitles are available!",
        postImage: ["assets/postImages/skz/4.jpg"],
        postDate: "13 Janurary 2021"},
           {id: 31,
        bandId: 0,
        socialMediaId: 1,
        postText: "[Stray Kids : SKZ-TALKER] Ep.46",
        postImage: ["assets/postImages/skz/7.jpg"],
        postDate: "11 Janurary 2021"},
           {id: 31,
        bandId: 0,
        socialMediaId: 1,
        postText: "",
        postImage: ["assets/postImages/skz/8.jpg","assets/postImages/skz/8a.jpg"],
        postDate: "8 Janurary 2021"},
           {id: 31,
        bandId: 0,
        socialMediaId: 1,
        postText: "Stray Kids 2ND #LoveSTAY 'SKZ'S CHOCOLATE FACTORY'",
        postImage: ["assets/postImages/skz/9.jpg"],
        postDate: "7 Janurary 2021"},
        //    {id: 31,
        // bandId: 0,
        // socialMediaId: 1,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //    {id: 31,
        // bandId: 0,
        // socialMediaId: 1,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //    {id: 31,
        // bandId: 0,
        // socialMediaId: 1,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //    {id: 31,
        // bandId: 0,
        // socialMediaId: 1,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
           {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "치킨이랑 쿼카 #뽁댕이#loveyou#STAY",
        postImage: ["assets/postImages/skz/16.jpg","assets/postImages/skz/16a.jpg"],
        postDate: "4 HOURS AGO"},
                     {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "#straykids #lovestay",
        postImage: ["assets/postImages/skz/15.jpg"],
        postDate: "9 HOURS AGO"},
                     {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "두바이 넘나넘나 재밌었당 ㅎㅎㅎ #StrayKids#STAY#IN스타그램#🦊",
        postImage: ["assets/postImages/skz/14.jpg"],
        postDate: "1 DAY AGO"},
                     {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "살아있음을 느꼈다 고마워요 두바이랑 리야드 안녕👋👋",
        postImage: ["assets/postImages/skz/13.jpg"],
        postDate: "1 DAY AGO"},
                     {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "사랑합니다 모두들 #loveyou#STAY#EXPO2020DUBAI",
        postImage: ["assets/postImages/skz/12.jpg"],
        postDate: "1 DAY AGO"},
                     {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "",
        postImage: ["assets/postImages/skz/11.jpg"],
        postDate: "1 DAY AGO"},
                     {id: 31,
        bandId: 0,
        socialMediaId: 2,
        postText: "너무 재밌자나ㅏ!! 두바이!!! 즐거웠어요!!👍👍 #리노는기여어#Expo2020Dubai",
        postImage: ["assets/postImages/skz/10.jpg"],
        postDate: "2 DAYS AGO"},
        //              {id: 31,
        // bandId: 0,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //              {id: 31,
        // bandId: 0,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""},
        //              {id: 31,
        // bandId: 0,
        // socialMediaId: 2,
        // postText: "",
        // postImage: [""],
        // postDate: ""}
          
  
    
];
