import { Post } from "./Posts";

export const POSTS: Post[] = [
    {id: 0,
    bandId: 1,
    socialMediaId: 0,
    postText: "멤버들 그리고 줴퀘 땡큐",
    postImage: ["assets/postImages/bts/post0.jpg"], //url do fotki
    postDate: "11:40 AM · 30 gru 2021"}, //tez string bo zalezy od social media

    {id: 1,
    bandId: 1,
    socialMediaId: 0,
    postText: "아 생일축하한다 브로",
    postImage: [], //url do fotki
    postDate: "9:04 AM · 30 gru 2021"}, //tez string bo zalezy od social media

    {id: 2,
    bandId: 1,
    socialMediaId: 0,
    postText: "마이 브로 태형아\n 너가 부탁한 사진 올린다\n 사랑한다 -진",
    postImage: ["assets/postImages/bts/post2.jpg"], //url do fotki
    postDate: "9:03 AM · 30 gru 2021"}, //tez string bo zalezy od social media

    {id: 3,
        bandId: 1,
        socialMediaId: 0,
        postText: "My love\n Happy birthday bro.\n #홉필름 \n #큰태형 \n #HAPPYVDAY \n #태형이와아미는_꽃길을걷고있어",
        postImage: ["assets/postImages/bts/post3a.jpg", "assets/postImages/bts/post3b.jpg", "assets/postImages/bts/post3c.jpg", "assets/postImages/bts/post3d.jpg"], //url do fotki
        postDate: "6:52 PM · 29 gru 2021"}, //tez string bo zalezy od social media
  
    {id: 4,
        bandId: 1,
        socialMediaId: 0,
        postText: "아 이게 인스타감성이었나?",
        postImage: [], //url do fotki
        postDate: "6:52 PM · 9 gru 2021"}, //tez string bo zalezy od social media
  
      {id: 5,
        bandId: 1,
        socialMediaId: 0,
        postText: "my name is v 삼성 보고있나",
        postImage: [], //url do fotki
        postDate: "4:00 PM · 9 gru 2021"}, //tez string bo zalezy od social media
   {id: 6,
        bandId: 1,
        socialMediaId: 0,
        postText: "Hundreds of millions of stars ⭐ (it's not photoshopped)",
        postImage: ["assets/postImages/bts/post6.jpg"], //url do fotki
        postDate: "4:00 AM · 8 gru 2021"}, //tez string bo zalezy od social media
  {id: 7,
        bandId: 1,
        socialMediaId: 0,
        postText: "진형 생일이 왠지 기네?\n 햅뻘떼쁘뤄",
        postImage: ["assets/postImages/bts/post7.jpg"],
        postDate: "4:00 AM · 5 gru 2021"}, 
    {id: 8,
        bandId: 1,
        socialMediaId: 0,
        postText: "ㅋㅋㅋㅋㅋㅋㅋ",
        postImage: ["assets/postImages/bts/post8.jpg"],
        postDate: "4:00 PM · 4 gru 2021"}, 
      {id: 9,
        bandId: 1,
        socialMediaId: 0,
        postText: "ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 내 사진첩에 유일한 형 엽사다.\n 진짜 다 잘생겨서 그나마 찾은게 이거야\n형 많이 사랑하고 생일 축하해 형\n생일 축하해",
        postImage: ["assets/postImages/bts/post9.jpg"],
        postDate: "2:00 PM · 4 gru 2021"}, 
      {id: 10,
        bandId: 1,
        socialMediaId: 0,
        postText: "태형",
        postImage: [],
        postDate: "1:00 PM · 4 gru 2021"}, 
      {id: 11,
        bandId: 1,
        socialMediaId: 0,
        postText: "쫜 생일축하해~",
        postImage: [],
        postDate: "11:00 AM · 4 gru 2021"}, 
      {id: 12,
        bandId: 1,
        socialMediaId: 0,
        postText: "늘 대리 만족을 해주는 얼굴\n #WWH 우리형 생일축하해요 \n사랑해 형!!건강하자!!",
        postImage: ["assets/postImages/bts/post12a.jpg","assets/postImages/bts/post12b.jpg","assets/postImages/bts/post12c.jpg","assets/postImages/bts/post12d.jpg"],
        postDate: "2:00 PM · 3 gru 2021"}, 
      {id: 13,
        bandId: 1,
        socialMediaId: 0,
        postText: "잊지 않을게요\n사랑합니다",
        postImage: ["assets/postImages/bts/post13a.jpg", "assets/postImages/bts/post13b.jpg"],
        postDate: "4:00 PM · 4 gru 2021"}, 
      {id: 14,
        bandId: 1,
        socialMediaId: 0,
        postText: "7FATES: CHAKHO is now coming.\nDon’t miss out the unreleased behind the scenes!",
        postImage: ["assets/postImages/bts/post14.jpg"],
        postDate: "4:00 PM · 4 gru 2021"}, 
      {id: 15,
        bandId: 1,
        socialMediaId: 1,
        postText: "Every moment we connected this year🌏 were our most Butter-ful moments, #BTSARMY! Thank you for a Butterful 2021",
        postImage: [],
        postDate: "18 grudnia 2021 o 16:00 "}, 
      {id: 16,
        bandId: 1,
        socialMediaId: 1,
        postText: "We had so much fun at iHeartRadio’s Jingle Ball this year, and now you can watch our performance tonight!💜 Put your TVs on The CW at 8/7c!",
        postImage: ["assets/postImages/bts/post16.jpg"],
        postDate: "16 grudnia 2021"}, 
      {id: 17,
        bandId: 1,
        socialMediaId: 1,
        postText: "Every day feels like holidays with #BTS_Butter (Holiday Remix)! 🎁\n☃Listen now: https://ingrv.es/butterholidayremix",
        postImage: [],
        postDate: "5 grudnia 2021"}, 
      {id: 18,
        bandId: 1,
        socialMediaId: 1,
        postText: "This is a huge honor🙏 Thanks to everyone who supports our music journey! 💜 Recording Academy / GRAMMYs  #GRAMMYs #BTS #방탄소년단",
        postImage: ["assets/postImages/bts/post18.jpg"],
        postDate: "24 listopada 2021"}, 
      {id: 19,
        bandId: 1,
        socialMediaId: 1,
        postText: "BTS PERMISSION TO DANCE ON STAGE - LA \nOfficial Merch Booth Map | 공식 상품 부스 맵\n📅NOV 26~28 , NOV 30~DEC 2 (PST)\n📍LA SoFi STADIUM",
        postImage: ["assets/postImages/bts/post19a.jpg","assets/postImages/bts/post19b.jpg"],
        postDate: "24 listopada 2021"}, 
      {id: 20,
        bandId: 1,
        socialMediaId: 2,
        postText: "",
        postImage: ["assets/postImages/bts/post20a.jpg","assets/postImages/bts/post20b.jpg","assets/postImages/bts/post20c.jpg","assets/postImages/bts/post20d.jpg","assets/postImages/bts/post20e.jpg","assets/postImages/bts/post20f.jpg","assets/postImages/bts/post20g.jpg","assets/postImages/bts/post20h.jpg","assets/postImages/bts/post20i.jpg","assets/postImages/bts/post20j.jpg"],
        postDate: "2 listopada 2021"},
  
                {id: 21,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA MAP 🗺",
        postImage: ["assets/postImages/bts/post21.jpg"],
        postDate: "8 tyg."},
                {id: 22,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA OFFLINE 🏟\nCONCERT | MERCHANDISE | LIVE PLAY",
        postImage: ["assets/postImages/bts/post22.jpg"],
        postDate: "8 tyg."},
                {id: 23,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA ONLINE 🖥\nONLINE LIVE STREAMING,
        postImage: ["assets/postImages/bts/post23.jpg"],
        postDate: "8 tyg."},
                {id: 24,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post24.jpg"],
        postDate: "8 tyg."},
                {id: 25,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post25.jpg"],
        postDate: "8 tyg."},
                {id: 26,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post26.jpg"],
        postDate: "8 tyg."},
                {id: 27,
        bandId: 1,
        socialMediaId: 2,
        postText: "OW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post27.jpg"],
        postDate: "8 tyg."},
                {id: 28,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post28.jpg"],
        postDate: "8 tyg."},
                {id: 29,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO ENJOY BTS PERMISSION TO DANCE ON STAGE - LA",
        postImage: ["assets/postImages/bts/post29.jpg"],
        postDate: "12 tyg."},
        {id: 30,
        bandId: 1,
        socialMediaId: 2,
        postText: "HOW TO DANCE WITH BTS - ONLINE STREAMING GUIDE\n- 티켓 구매 : 위버스샵\n- 시청 페이지: venewlive.com/concerts/bts-ptd-onstage\n- 판매기간\n[사운드체크 스트리밍 포함 상품]\n▶ 2021년 10월 1일(금) 12 PM ~ 2021년 10월 24일(일) 2:59 PM (KST)",
        postImage: ["assets/postImages/bts/post30.jpg"],
        postDate: "8 tyg."},
  
    
];
